### ISSUE TITLE
Plugin not showing up

### ISSUE THREAD

**Issue by christianbraun** [3dcitydb/plugin-spreadsheet-generator#2]
Hi, the plugin is not showing up in the Importer/Exporter app.
I am running MacOs Mojave, used the Installer

Thanks in advance,
Christian

**Comment by Son-HNguyen** [comment]
Hi Christian,

I used the 4.2.0 installer on Mac Mojave 10.14.3 and everything works fine. Make sure you have the plugin checked during installation.

**Comment by Sassimion** [comment]
Hi,

I have a problem to access the attribute. I upload it on google spreadsheet but it doesn't appear on Cesium.

Thanks in advance.

Sue

![Capture1](https://user-images.githubusercontent.com/72721595/137281085-05c926a4-8acb-4d7b-a8ac-e9c84df6c632.JPG)

**Comment by yaozhihang** [comment]
The question above is duplicated here:
https://github.com/3dcitydb/3dcitydb-web-map/issues/71
